### ISSUE TITLE
No colored buttons on GNOME 3.12

### ISSUE THREAD

**Issue by brunelli** [elitalobo/GSOC2014#1]
Hello!
I've just cloned gnome-calculator from git.gnome.org, applied all the patches from here and installed, but all the buttons are still grey.
At first I thought some patch wasn't applied, but I've repeat all the steps again, and certified that all the patches was sucessfully applied.
So, is this something that will only work with GTK >= 3.13 or do you think I'm doing something wrong?
Cheers, Ian.

**Comment by elitalobo** [comment]
Hi,
The patch only colors the clear button in red and result button in blue. As far as I have tested it works with GTK >= 3.14 . Kindly upgrade your GTK version and let me know if you still face any problem.
Sorry for the delay in reply. :/

**Comment by brunelli** [comment]
Hey, no problem.

I'm currently running GTK 3.14.4 and still have no color on the buttons.

The patches were applied with no flaws. The `gnome-calculator.css` file was created, but it isn't found at runtime:

```
** (gnome-calculator:4015): WARNING **: math-buttons.vala:650: Error loading css styles from data/gnome-calculator.css:Failed to import: Erro ao abrir arquivo: Arquivo ou diretório não encontrado
```

Are you sure that it is installed [on the right place]?
